name: current_a_la_te
description: Tennis App to connect players around the country by rceb98.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  build_runner: ^2.10.3
  dio: ^5.9.0
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.0.5
  go_router: ^16.3.0
  intl: ^0.20.2
  json_serializable: ^6.11.1
  multiple_result: ^5.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
